@startuml class diagram 

enum Relationship {
   +Paternal_Uncle 
   +Maternal_Uncle
   +Paternal_Aunt
   +Maternal_Aunt
   +Sister_In_Law
   +Brother_In_Law
   +Son
   +Daughter
   +Siblings
}

enum Gender {
    +Male
    +Female
}

enum Message {
    +Child_Addition_Failure
    +Child_Addition_Success
    +Member_Search_Failure
    +Relationship_Search_Failure
    +Spouse_Addition_Failure
    +Spouse_Addition_Success
    +King_Queen_Addition_Failure
    +King_Queen_Addition_Success
}

class App {
    -commands: string[]
    +readFile(filePath: string): boolean
    +runCommands()
}

class FamilyTree {
    +king: Father
    +queen: Mother
    +addKingQueen(kingName: string, queenName: string): void
    +addChild(montherName: string, childName: string, gender: Gender): string
    +addSpouse(name: string, spouseName: string, gender: Gender): string
    +getRelationship(name: string, relationship: Relationship): string
    -findFamilyMember(name: string): FamilyMember | null
    -buildFamilyTree(filePath: string): boolean
}

abstract FamilyMember {
    +name: string
    +gender: Gender
    +getRelationship(relationship: Relationship): string[]
    +addSpouse(spouseName: string, gender: Gender): boolean
}

class Father {
    +child: Child[]
    +spouse: Mother
}

class Mother {
    +child: Child[]
    +spouse: Father 
    +addChild(childName: string, genter: Gender): boolean
}

class Child {
    +father: Father
    +mother: Mother
}

FamilyTree "1..*" o-- "*" FamilyMember

FamilyMember <|-- Father
FamilyMember <|--  Mother
FamilyMember <|--  Child 

@enduml