@startuml domain model

class Gorilla {
    name: string
    gender: string
}

class Mother {
    child: Child[]
    spouse: Father
}

class Father {
    child: Child[]
    spouse: Mother
}

class Child {
    father: Father
    mother: Mother
}

Gorilla <|-- Mother
Gorilla <|-- Father
Gorilla <|-- Child

Mother "1" -- "*" Child
Father "1" -- "*" Child

Mother -- Father

@enduml